-- Serviços iniciais (valores 0.00 para edição posterior)
INSERT INTO services (categoria, nome, unidade, preco_final, preco_corporativo, ativo) VALUES
('CORTINAS','Forro de Cortina','m2',0,0,1),
('CORTINAS','Cortina de Seda','m2',0,0,1),
('CORTINAS','Cortina demais tecidos','m2',0,0,1),
('CORTINAS','Cortina de Linho','m2',0,0,1),
('CORTINAS','Cortina Blackout','m2',0,0,1),
('PERSIANAS','Persiana Rollon/Romana','m2',0,0,1),
('PERSIANAS','Persiana de Fita','m2',0,0,1),
('CARPETE','Lavagem de Carpete','m2',0,0,1),
('ESTOFADOS','LAVAGEM : VELUDO/CAPITONÊ/RETRÁTIL','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE SOFÁS SIMPLES','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE POLTRONAS PEQUENAS','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE POLTRONAS GRANDES','peca',0,0,1),
('ESTOFADOS','CADA LAVAGEM DE CADEIRAS JANTAR ASSENTO','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE CADEIRAS JANTAR Assento e Encosto','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE ALMOFADAS DECORATIVAS Pequena','peca',0,0,1),
('ESTOFADOS','LAVAGEM DE ALMOFADAS DECORATIVAS Grande','peca',0,0,1),
('ESTOFADOS','IMPERMEABILIZAÇÃO ESTOFADOS por assento','peca',0,0,1),
('ESTOFADOS','IMPERMEABILIZAÇÃO DE CADEIRAS','peca',0,0,1),
('TAPETES','Lavagem de Tapetes PERSAS','m2',0,0,1),
('TAPETES','Lavagem tapete:KILINS/ NACIONAL/NYLON','m2',0,0,1),
('TAPETES','Lavagem de Tapetes MIKONOS/BAHARI','m2',0,0,1),
('TAPETES','Lavagem Tapetes Simples (Tabacow/Belga)','m2',0,0,1),
('TAPETES','Lavagem tapete SEDA','m2',0,0,1),
('TAPETES','LAVAGEM + GOMA (KILINS E ARRAIOLOS)','m2',0,0,1),
('TAPETES','Franjas  DE LÃ e ALGODÃO','ml',0,0,1),
('TAPETES','Franjas de Arraiolo','ml',0,0,1),
('TAPETES','Franjas c/ Kilim (Algodão)','ml',0,0,1),
('TAPETES','Franjas c/ Kilim de SEDA MERCERIZADA','ml',0,0,1),
('TAPETES','Franjas de SEDA MERCERIZADA','ml',0,0,1),
('TAPETES','Franjas SEDA PURA','ml',0,0,1),
('TAPETES','Ponto Parada','peca',0,0,1),
('TAPETES','Cordão (Á MÃO)','peca',0,0,1),
('TAPETES','Debrum (Á MÁQUINA)','peca',0,0,1),
('TAPETES','Resina','peca',0,0,1),
('TAPETES','Aplicação de Goma','peca',0,0,1),
('TAPETES','Tela Anti-derrapante','m2',0,0,1),
('TAPETES','Forro Nacional','m2',0,0,1),
('TAPETES','Forro de Algodão','m2',0,0,1),
('TAPETES','Forro de Gorgurão','m2',0,0,1),
('TAPETES','Borda de Couro Ecológico ou tecido','ml',0,0,1),
('TAPETES','Borda de Tecido','ml',0,0,1),
('TAPETES','Fita de Couro (lateral)','ml',0,0,1),
('TAPETES','Chá nas Franjas','peca',0,0,1),
('TAPETES','Barra Virada','peca',0,0,1),
('TAPETES','Cantoneiras','peca',0,0,1),
('TAPETES','Aplicação de Selante','peca',0,0,1),
('TAPETES','Colocação de madeira c/ bainha','peca',0,0,1),
('TAPETES','Acabamento c/ fita no verso','peca',0,0,1),
('TAPETES','Impermeabilização de Tapetes','m2',0,0,1);
